global using MediatR;
global using WembleyScada.Domain.SeedWork;
global using WembleyScada.Domain.AggregateModels.LineAggregate;
global using WembleyScada.Domain.AggregateModels.StationAggregate;
global using WembleyScada.Domain.AggregateModels.EmployeeAggregate;
global using WembleyScada.Domain.AggregateModels.ShiftReportAggregate;
global using WembleyScada.Domain.AggregateModels.ReferenceAggregate;
global using WembleyScada.Domain.AggregateModels.ProductAggregate;
global using WembleyScada.Domain.Exceptions;
